# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
#Exception
    app.json_exception_listener:
          class: AppBundle\Listener\JsonExceptionListener
          tags:
              - { name: 'kernel.event_listener', event: 'kernel.exception', method: 'onKernelException' }

    app.place.normalizer:
        class: AppBundle\Serializer\PlaceNormalizer
        parent: serializer.normalizer.object
        arguments: ['@doctrine']
        tags:
            -  { name: serializer.normalizer }

    app.user.normalizer:
        class: AppBundle\Serializer\UserNormalizer
        parent: serializer.normalizer.object
        arguments: ['@doctrine']
        tags:
            -  { name: serializer.normalizer }

    app.review.normalizer:
        class: AppBundle\Serializer\ReviewNormalizer
        autowire: true
        tags:
            -  { name: serializer.normalizer }
#Security

    app.api_token_authenticator:
        class: AppBundle\Security\ApiTokenAuthenticator

    app.doctrine_listener:
        class: AppBundle\Security\PasswordListener
        arguments: ['@security.password_encoder']
        tags:
            - { name: doctrine.event_subscriber }
